development:
  adapter: postgresql
  encoding: unicode
  database: sikon_development
  pool: 5
  username: sikon
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: sikon_test
  pool: 5
  username: sikon
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: sikon_production
  pool: 5
  username: sikon
  password: root


