User.create(rf: '1234567', password: '123456')

Motorista.create(nome:'AGUINALDO REIS SANTOS', rf:'39952', cargo:'ENC.SET.I/ART.SUPLEM', secao_original: '', secao_atual:'D. PRODUCAO',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'ALEXSANDER DIAS SOARES', rf:'37772', cargo:'FISC/SERVICOS-DAI-08', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'ALVIMAR FELIX SANTOS', rf:'33372', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'ANTONIO CARLOS LOPEZ', rf:'37802', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'MAN.A.VERDES',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'ANTONIO FIRMINO DOS SANTOS', rf:'36312', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'CARLOS EDUARDO PEREIRA', rf:'30212', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'CLAUDIO OSHIRO', rf:'40462', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'ADM.CEMIT.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'CLOVIS ALVES DA SILVA', rf:'32872', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'DANIEL DOS REIS', rf:'27692', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'C.N.CACHOE.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'DANIEL PEREIRA DA SILVA', rf:'37882', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'EDILSON PINHEIRO REIS', rf:'32142', cargo:'FISC/SERVICOS-DAI-08', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'EDUARDO CERQUEIRA RODRIGUES', rf:'28332', cargo:'AG. APOIO N-II CAT.3', secao_original: '', secao_atual:'FM 21',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'FABIO MARQUES DE LIMA', rf:'30452', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'MANUT. DA SEDE',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'GILBERMARIO DOS S.SIMPLICIO', rf:'38822', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'GILBERTO BUENO LUQUE', rf:'10172', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'AG.Q. PARADA',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'GILBERTO LUSVARDI', rf:'32252', cargo:'FISC/SERVICOS-DAI-08', secao_original: '', secao_atual:'EXP. TRAF',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'GUILHERME SUVIEIS', rf:'33172', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'VEL. S. PAULO',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'HERMELINDO SILVIO JOSE ROMANO', rf:'38012', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'IRINEU SPIRANDELLI', rf:'37182', cargo:'ENC.SET.I/OF.MECANIC', secao_original: '', secao_atual:'Crematório',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'JOAO BATISTA FRANCISCO', rf:'37942', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'ALMOX.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'JOAO CARLOS DE BIAZZI', rf:'19561', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'JOAOSITO SABINO DOS SANTOS', rf:'37912', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'AG. H.S.P.M.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'JOAQUIM FERREIRA DOS SANTOS', rf:'26552', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'ETQ URNAS CAIX',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'JORGE SOARES', rf:'33592', cargo:'CHEFE SEC/TRAFEGO', secao_original: '', secao_atual:'Ch. DIV.DE TRANS.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'JOSE MARCELO DANTAS', rf:'37812', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'S. SOC./ FM.21',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'JOSE MARIA COSTA', rf:'37442', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'AG. FORMOSA',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'LUIZ CARLOS DE MOURA FLORENCIO', rf:'30242', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'MARCOS MOREIRA AVELINO', rf:'37462', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'MAURICIO LAURO GONCALVES', rf:'33922', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'MOACIR ROCHA JUNIOR', rf:'27842', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'AG.Q. PARADA',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'MOACIR SERRA NATAL', rf:'39592', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'AG.CENTRAL',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'MURILO ALTRO GOMES', rf:'38052', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'S. PESSOAL',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'ODIMAS FERREIRA DA SILVA', rf:'20112', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'EST. URNAS CAIX',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'OLAVIO DE FATIMO OCCHIUZZI', rf:'37062', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'VELORIO ARACA',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'OSVALDO BENTO DA SILVA', rf:'38062', cargo:'ENC.S.II/EST.MAT.PRO', secao_original: '', secao_atual:'ALMOX.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'OSWALDO DA ROCHA', rf:'37492', cargo:'ENC.SET.I/MARC.CAIX.', secao_original: '', secao_atual:'MAN. DA SEDE',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'PAULO ROBERTO PEREIRA DA SILVA', rf:'37832', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'ROBERTO DE AMIGO', rf:'18862', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'AG.CENTRAL',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'SILVIO MARTINES', rf:'32942', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'FISCALIZ.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'SPARTACO PASSERO FILHO', rf:'39622', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'Velório Santana',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'VALDIR PEDRO DA SILVA', rf:'34782', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'AGENCIA H.S.P.M.',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'VALDOMIRO DE JESUS', rf:'26682', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'AG.ARACA',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'WALMIR CARDOMINGO', rf:'36492', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'S. PEDRO',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'WANDERLEY LEMES DE SOUZA', rf:'33302', cargo:'AG. APOIO N-II CAT.3', secao_original: '', secao_atual:'C.SANTANA',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'EDUARDO FERNANDES ALVES', rf:'39662', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'VISTORIA',pontuacao:'',local:'Outras Áreas',status:'Ativo')
Motorista.create(nome:'TADEU SCALISSE', rf:'37952', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'VISTORIA',pontuacao:'',local:'Outras Áreas',status:'Ativo')

Motorista.create(nome:'ALEX SANDER ALBER ALVES', rf:'39952', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'ANDERSON LUIS DOS S. PEREIRA', rf:'37772', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'ANTONIO CARLOS DIAS LIMA', rf:'33372', cargo:'ASSIST.ADM.DAI-06', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'ANTONIO RIBEIRO S.DA ROCHA', rf:'37802', cargo:'ENC.S.I/ENT.MONT.URN', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'BRUNO AYRES DE NOGUEIRA', rf:'36312', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'DIEMERSON PEREIRA DE MATOS', rf:'30212', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'DJANILDO PEDRO DE LIMA', rf:'40462', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'ELCIO MARTINS COSTA', rf:'32872', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'FRANCISCO DE ASSIS FERREIRA', rf:'27692', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'FRANCISCO DE ASSIZ VIEIRA', rf:'37882', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'GLAUBER ARAUJO MAIA', rf:'32142', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'JOHNNY LUIS ARAUJO', rf:'28332', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'JORGE LUIZ ANTONIO', rf:'30452', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'LUIS FELIPE PEREIRA BARLOTTI', rf:'38822', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'LUIS IGNACIO BENUCCI', rf:'10172', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'MARIO OUTUMURO MEDEIROS', rf:'32252', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'MARIO SERGIO PEREIRA', rf:'33172', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'MIKE JENNISON BEZERRA', rf:'38012', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'ROGERIO ARRUDA', rf:'37182', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')
Motorista.create(nome:'VALDIR FERNANDES', rf:'37942', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Ativo')

Motorista.create(nome:'ADEMIR RAMOS GUEDES', rf:'32802', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'ADILSON BENEDITO C.CACILDO', rf:'33432', cargo:'ENC.S.I/TAPEC.AUTOS', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'AILTON LUCIO NERES', rf:'37822', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'ALVARO DOS SANTOS COSTA', rf:'12382', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'ANTONIO ROBERTO SANTOS SOUZA', rf:'24161', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'ANTONIO SANTOS DOS ANJOS', rf:'37192', cargo:'ENC.SET.I/ELET.VEIC', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'CAJARANO PEREIRA DOS SANTOS', rf:'21342', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'CARLOS ROBERTO DE OLIVEIRA', rf:'38942', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'CARLOS ROBERTO GARCIA', rf:'32122', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'CARLOS ROBERTO LOPES', rf:'33222', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'CLAUDIO DE OLIVEIRA SANTOS', rf:'41022', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'CLAUDIO GONCALVES DA SILVA', rf:'31202', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'CRISPIM VIDAL DE SANTANA', rf:'38112', cargo:'ENC.SET.I/FORRACAO', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'DANIEL DE SOUZA', rf:'37332', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'DANIEL RODRIGUES FILHO', rf:'30362', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'DANIEL STAR DE SOUZA CRUZ', rf:'39912', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'DENIVALDO LOPES DA SILVA', rf:'32202', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'EDEVALDO BENATO SANTANA', rf:'32132', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'EDISON FERNANDES', rf:'38092', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'EDISON RODRIGUES', rf:'36702', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'EDSON DA SILVA PEREIRA', rf:'38892', cargo:'ENC.SET.I/BORRACHARI', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'EURICO DA CRUZ', rf:'37262', cargo:'ENC.S.I/AB.LUBR.VEIC', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'EZIO RIJO BORGES', rf:'22952', cargo:'AG. APOIO N-II CAT.3', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'FERNANDO CUSTODIO DA SILVA', rf:'37932', cargo:'ENC.S.I/CARPINTARIA', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'FRANCISCO ALVES DO NASCIMENTO', rf:'20052', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'FRANCISCO DE ASSIS MIRANDA', rf:'37162', cargo:'ENC.SET.I/COSTURA', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'GERALDO TEXEIRA LOPES', rf:'39942', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'GLAUCIO RUFINO DE MELO', rf:'40152', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'HENRIQUE FERREIRA', rf:'32092', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'INALDO RUFINO DE MELO', rf:'32922', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'ISAC ALENCAR REIS', rf:'33272', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'IVAN DA SILVA FERREIRA', rf:'26642', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JAIME LOPES SILVA', rf:'37042', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOAO BARBOSA', rf:'34722', cargo:'ENC.S.I/AB.LUBR.VEIC', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOAO DA CRUZ V. NOVA M. JUNIOR', rf:'40602', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JORGE JOSE FREUA', rf:'40582', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE ALVES NOGUEIRA', rf:'22912', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE ANTONIO MARTINS FERNANDES', rf:'26572', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE AUGUSTO MARTINS FERNANDES', rf:'22832', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE EDRIANO DA SILVA', rf:'40592', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE LOPES DE LIMA', rf:'39602', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE LUIZ CORREA DE MOURA', rf:'28112', cargo:'ASSIST.ADM.DAI-06', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE MARCIO DE PAULA', rf:'18942', cargo:'ENC.SET.I/ZELADORIA', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JOSE PATERNOSTRO', rf:'30272', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'JURANDI DE CASTRO MAROPO', rf:'33552', cargo:'AG. APOIO N-II CAT.2', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'MANOEL MINERVINO', rf:'38102', cargo:'ENC.SET.I/P.REV.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'MARCELO FERREIRA DE OLIVEIRA', rf:'40722', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'MARCIO DOS REIS PEREIRA', rf:'38882', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'MARCIO MACHADO', rf:'35202', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'MARCO ANTONIO BARRETO', rf:'12372', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'MAURO FERNANDES GARCIA', rf:'40672', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'MOISES DA SILVA MARTIMIANO', rf:'39552', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'NELSON HIROSHI OIDE', rf:'40852', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'OSMAR GARCIA FERREIRA', rf:'40662', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'OSVALDO COSTA', rf:'33322', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'PAULO DONIZETE DA SILVA', rf:'38002', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'PAULO EDUARDO FERNANDES', rf:'33312', cargo:'AG. APOIO N-II CAT.2', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'PAULO FILOMENO DE LIMA', rf:'39652', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'PAULO ROBERTO NUNES DA SILVA', rf:'39612', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'REGINALDO VIANA', rf:'27362', cargo:'MOTORISTA/QPA6E', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'RINALDO ALBINO PEREIRA', rf:'38132', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'ROBSON SERRANO VIEIRA', rf:'33132', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'RUBENS FREITAS DOS SANTOS', rf:'36662', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'SANDOVAL SANTINO DE AZEVEDO', rf:'37432', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'SERGIO LUIZ CARNEIRO', rf:'40102', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'SERGIO PEREIRA', rf:'41052', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'TABAJARA DOS SANTOS', rf:'35522', cargo:'ENC.SET.I/P.REV.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'VALDIR VIEIRA DE CAMPOS', rf:'29312', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'VALTER NATALINO NUNES', rf:'27872', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'VALTER SILVA', rf:'39632', cargo:'ENC.SET.I/FUNIL.VEIC', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'VANDERLEI TORTOSA MALICIA', rf:'27722', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'VICENTE DONIZETE M. FERNANDES', rf:'38842', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'WALDEMAR SILVA FILHO', rf:'37852', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')
Motorista.create(nome:'WALDIR DE OLIVEIRA', rf:'30122', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Ativo')

Motorista.create(nome:'ALFREDO DONIZETI DO PRADO', rf:'37392', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ALFREDO MATHIAS', rf:'26382', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ALMIRO DE ABREU', rf:'37242', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ALOISIO OLINTHO DE O. ROCHA', rf:'41072', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ALVARO MARTINS BATISTA', rf:'13512', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ANDERSON APARECIDO DE CARVALHO', rf:'34852', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ANTONIO CARLOS MINGUE', rf:'34662', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ARTUR FERREIRA CAPDEVILLA', rf:'36792', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'CARLOS ALBERTO GONCALVES', rf:'37302', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'CICERO MAGAYVER MARTINS COSTA', rf:'41162', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'CLAYTON MARQUES DE SOUSA', rf:'41272', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'CLOVIS ROBERTO DE FARIAS', rf:'28132', cargo:'AG. APOIO N-II CAT.3', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'EDISON SARRAFF', rf:'17862', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'EDUARDO MARTINEZ GUEBARA', rf:'37872', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'EDUARDO RIBEIRO DOS SANTOS', rf:'38072', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'EXPEDITO RAMOS DA SILVA', rf:'33072', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'FLAVIO APARECIDO PIROLA', rf:'36772', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'FLAVIO MEDEIROS DE FREITAS', rf:'9752', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'GERALDO OTAVIO BARBOSA', rf:'35482', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'GERIEL PIRES FRANCISCO', rf:'41152', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'GILMAR EUSTAQUIO DA SILVEIRA', rf:'32972', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'HEITOR MARCUS RODRIGUES', rf:'38152', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'HELIO JOSE DE OLIVEIRA', rf:'32392', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'JAIME PEREIRA DE RESENDE', rf:'35552', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'JESUALDO HENRIQUE DOURADO', rf:'37082', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'JOAO ALBERTO PESSOA FERREIRA', rf:'36962', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'JOAQUIM SIMOES CORDEIRO JUNIOR', rf:'36592', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'JOSE ANTONIO FERRINHA', rf:'28692', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'JOSE MORAES DE LIMA', rf:'36602', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'JOSE TEIXEIRA', rf:'32102', cargo:'ENC.SET.I/PINT.VEIC', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'LUCIANO LUIZ FILHO', rf:'36932', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'MANOEL APARECIDO DA COSTA', rf:'30132', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'MANOEL LEAO DA SILVA FILHO', rf:'22812', cargo:'AG. APOIO N-II CAT.4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'MANOEL RAFAEL DE LIRA', rf:'34762', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'MARIO APARECIDO ROVERON', rf:'33602', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'MARTINHO RODRIGUES', rf:'31172', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'MOTAURY CARVALHO DE LIMA', rf:'37922', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'NERIVALDO JOSE SANTANA REIS', rf:'37342', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'NILSON VENANCIO', rf:'37142', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'OSMAR RODRIGUES MASSE', rf:'32952', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'OTACILIO JULIO DA CRUZ', rf:'8772', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'RINALDO DA SILVA VAZ', rf:'28522', cargo:'ENC.SET.I/ZELADORIA', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ROGERIO FERNANDES BUENO', rf:'32812', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ROGERIO FERREIRA DE MOURA', rf:'34402', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'SEBASTIAO VIANA DE SOUZA', rf:'33382', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'SERGIO GONCALVES', rf:'37312', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'THIAGO DONIZETE MATHIAS', rf:'39892', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'ULYSSES DIAS LIMA', rf:'33572', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'WILSON ALVES DE OLIVEIRA', rf:'34752', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')
Motorista.create(nome:'WILSON MACEDO SILVA', rf:'38282', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Ativo')

Motorista.create(nome:'LUIZ ADOLFO LABOISSIERE', rf:'36892', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'VISTORIA',pontuacao:'',local:'Outras Áreas',status:'Licença Médica')
Motorista.create(nome:'ANTONIO TADEU MARTUZZO', rf:'41082', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Licença Médica')
Motorista.create(nome:'MARCOS SARAIVA PASSOS', rf:'39932', cargo:'ENC.S.II/BENS PATRIM', secao_original: '', secao_atual:'CONTABILIDADE',pontuacao:'',local:'Outras Áreas',status:'Licença Médica')
Motorista.create(nome:'MESSIAS ADRIANO MARQUES FILHO', rf:'25491', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Licença Médica')
Motorista.create(nome:'NELSON INACIO PINTO JUNIOR', rf:'36752', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Licença Médica')
Motorista.create(nome:'NORIVAL MARTINS DOS SANTOS', rf:'36802', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Licença Médica')
Motorista.create(nome:'VALTER LUCIANO B DA COSTA', rf:'38832', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Licença Médica')
Motorista.create(nome:'VANDERCI MENDES CARMONA', rf:'37362', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Licença Médica')
Motorista.create(nome:'EDSON CASTRO', rf:'33082', cargo:'MOTORISTA/QPA7E', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Licença Médica')
Motorista.create(nome:'CELIO DA SILVA HONORATO', rf:'31262', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Licença Médica')

Motorista.create(nome:'CARLOS ANDRE DE OLIVEIRA FERRO', rf:'41262', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Processo Administrativo de Falta')
Motorista.create(nome:'DERMEVAL RAMOS NASCIMENTO', rf:'41192', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Processo Administrativo de Falta')
Motorista.create(nome:'JESSE MARCOS DOMINGUES', rf:'41002', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Processo Administrativo de Falta')

Motorista.create(nome:'AIRTON MARTINS ALVES', rf:'41062', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'Protocolo',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'ARISTEU DE LIMA CIRILO', rf:'33462', cargo:'AG. APOIO N-II CAT.2', secao_original: '', secao_atual:'AGENCIA H.S.P.M.',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'AUDECIO PEREIRA FELIX', rf:'36742', cargo:'ENC.S.I/EXPED.U.CAIX', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Readaptado')
Motorista.create(nome:'EDSON PROCOPIO DA SILVA', rf:'39562', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Readaptado')
Motorista.create(nome:'ELIO JOSE DOMINGOS', rf:'41202', cargo:'AG. APOIO N-I CAT.1', secao_original: '', secao_atual:'RECORPS',pontuacao:'',local:'RECORPS',status:'Readaptado')
Motorista.create(nome:'GERALDO JOSE DA SILVA', rf:'35032', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Readaptado')
Motorista.create(nome:'JORGE RODRIGUES', rf:'33042', cargo:'AG. APOIO N-II CAT.1', secao_original: '', secao_atual:'PROTOCOLO',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'JOSE CARLOS GOMES', rf:'26402', cargo:'AG. APOIO N-II CAT.5', secao_original: '', secao_atual:'MANUT.AREAS VERDES',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'JOSE EDUARDO DE ALMEIDA BARROS', rf:'34692', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'TRAF V. MARIAN.',pontuacao:'',local:'TRAF V. MARIAN.',status:'Readaptado')
Motorista.create(nome:'JOSE FRANCISCO DA SILVA', rf:'36632', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'CEMIT.PARELHEIROS',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'JOSE GERALDO DOS SANTOS', rf:'33402', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'VELORIO ARACA',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'JOSE LUIZ DA SILVEIRA', rf:'27932', cargo:'AG. APOIO N-II CAT.3', secao_original: '', secao_atual:'CEMIT.QUARTA PARADA',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'MARCIO SERGIO SANCHES', rf:'37782', cargo:'PROG.EXPEDIDOR/DAI-4', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Readaptado')
Motorista.create(nome:'MINERVINO TAVARES O FILHO', rf:'37962', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'VELORIO ITAQUERA',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'RENATO ARAUJO SILVA', rf:'38862', cargo:'AG. APOIO N-I CAT.4', secao_original: '', secao_atual:'AG.CENTRAL',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'SATURNINO FERREIRA DOS SANTOS', rf:'36832', cargo:'AG. APOIO N-I CAT.5', secao_original: '', secao_atual:'PROTOCOLO',pontuacao:'',local:'Outras Áreas',status:'Readaptado')
Motorista.create(nome:'VALDO DE SIMONI', rf:'37402', cargo:'ENC.S.I/AB.LUBR.VEIC', secao_original: '', secao_atual:'TRAF V. GUILH.',pontuacao:'',local:'TRAF V. GUILH.',status:'Readaptado')





